name: Upload All Files to S3

on:
  push:
    branches:
      - main  # or any branch you prefer

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Upload all files to S3
      run: |
        aws s3 cp . s3://${{ secrets.S3_BUCKET }}/ --recursive --exclude ".git/*" --exclude ".github/*"
